### ISSUE TITLE
v4的版本运行不了

### ISSUE THREAD

**Issue by zhouyihd** [DingHsun/PaddleOCR-cpp#10]

**Comment by DingHsun** [comment]
請問您出現的錯誤Log是什麼，方便截圖提供嗎?

**Comment by zhouyihd** [comment]
非常的感谢您的回复，好像是因为使用的onnxruntime的版本太高了，您这个不支持高版本的onnxruntime吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "黃鼎勲 (Ding Hsun ***@***.***&gt;; 
发送时间: 2024年9月9日(星期一) 上午10:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DingHsun/PaddleOCR-cpp] v4的版本运行不了 (Issue #10)















请问您出现的错误日志是什么，方便截图提供吗？

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
***@***.*** &gt;

**Comment by DingHsun** [comment]
目前僅在onnx1.12.1使用過，可以嘗試看看上述版本，如果可以正常運行那表示版本需要一致才行。

**Comment by zhouyihd** [comment]
推理速度好像挺慢的，目前cpu上是将近1秒一张
