### ISSUE TITLE
关于方向分类器的疑惑

### ISSUE THREAD

**Issue by pcycccccc** [DingHsun/PaddleOCR-cpp#8]
感谢您的项目分享，我通过构建您的代码，测试过是可以使用的！

但是我有个问题想跟您请教，我想知道，如果我的方向是水平的，文字的类别也是固定英文的，有必要进行方向分类器的预测吗？因为我去掉了方向分类检测的代码，发现输出结果是一样的。

另外，比如我的图像如下所示，但是推理输出的结果好像是反着的（方向分类检测有无，都是这样的结果）。
![image](https://github.com/DingHsun/PaddleOCR-cpp/assets/108455796/e52ae0bb-aa43-48a1-8503-7a36936818fc)
![image](https://github.com/DingHsun/PaddleOCR-cpp/assets/108455796/7bd6f67a-bab6-4951-b3c7-836b53248e52)

**Comment by DingHsun** [comment]
是的方向檢測的代碼是先寫好的，在我的實例中並未使用到，若有需要的話就得自行研究囉，感謝!
