### ISSUE TITLE
速度好慢啊

### ISSUE THREAD

**Issue by huangguifeng** [DingHsun/PaddleOCR-cpp#9]
c++ 推理，比python 推理还慢很多，这是什么问题

**Comment by DingHsun** [comment]
請問是建構後只進行一次推理後就解構嗎?據我使用上來說每次建構後的第一次推理都會較久，後續就會快很多。
最近在研究TensorRT加速模型推理，可以參考這篇https://github.com/noahmr/yolov5-tensorrt。
在Yolov5中的onnx模型轉為TensorRT的推理上快了將近一倍，可以試著套用看看，若有新的C++ API會再通知您，感謝!
